Revert "net: wireless: bcmdhd: additional length check for BRCM EVENT frame."
error: unknown type name 'bcm_event_msg_u_t'

This reverts commit 22bd6f9dc199bfd9a4e23c821d76665ec8f6f16f.

Change-Id: I83a49494c763481f1728219f4229641e8b4d34f6